# Generated by Django 2.1.1 on 2018-09-23 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_model', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('layover', models.IntegerField()),
                ('depature', models.TimeField()),
                ('arrival', models.TimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='routes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.RouteSchedule'),
        ),
    ]
